export const DEFAULT_SIGN_IN = "SIGN_IN";
export const GOOGLE_AUTH_SIGN_IN = "GOOGLE_AUTH_SIGN_IN";
export const GOOGLE_AUTH_SIGN_OUT = "GOOGLE_AUTH_SIGN_OUT";
export const SIGN_OUT = "SIGN_OUT";
export const DEFAULT_REGISTER_ATTEMPT = "DEFAULT_REGISTER_ATTEMPT";
export const GOOGLE_REGISTER_ATTEMPT = "GOOGLE_REGISTER_ATTEMPT";
